export const en = {
    // General
    dashboard: "Dashboard",
    saveChanges: "Save Changes",
    continue: "Continue",
    back: "Back",
    cancel: "Cancel",
    owner: "Owner",
    admin: "Admin",
    editor: "Editor",
    viewer: "Viewer",
    logout: "Log Out",
    settingsMenu: "Settings",

    // Navigation
    nav: {
        analytics: "Analytics",
        audit: "Chat Audit",
        knowledge: "Knowledge Base",
        playground: "Playground",
        usage: "Detailed Usage",
        billing: "Billing & Plans",
        planUsage: "Plan Usage"
    },

    // Auth
    auth: {
        welcomeBack: "Welcome Back",
        createAccount: "Create Account",
        loginPhoneTitle: "Login with Phone",
        loginSubtitle: "Sign in to access your dashboard",
        registerSubtitle: "Start building your AI assistant",
        phoneSubtitle: "We'll send you a one-time password",
        emailLabel: "Email Address",
        emailPlaceholder: "name@company.com",
        passwordLabel: "Password",
        passwordPlaceholder: "••••••••",
        phoneLabel: "Phone Number",
        phonePlaceholder: "+1 (555) 000-0000",
        signInBtn: "Sign In",
        signUpBtn: "Sign Up",
        sendOtpBtn: "Send OTP",
        orContinueWith: "Or continue with",
        noAccountQ: "Don't have an account?",
        signUpLink: "Sign up",
        hasAccountQ: "Already have an account?",
        logInLink: "Log in",
        loginPhoneLink: "Login with phone instead"
    },

    // Onboarding
    onboarding: {
        title: "Project Setup",
        step1: "Project Details",
        step1Desc: "Name & Scope",
        step2: "AI Persona",
        step2Desc: "Define Purpose",
        step3: "Ready to Launch",
        step3Desc: "Generate APIs",
        pane1Title: "Let's create your AI Assistant",
        pane1Sub: "What should we call this project?",
        projectNameLabel: "Project Name",
        projectNamePlaceholder: "e.g. Acme Corp Support",
        projectDescLabel: "Project Description",
        projectDescPlaceholder: "Briefly describe your project goals (max 50 words)",
        projectDomainLabel: "Primary Domain (Optional)",
        projectDomainPlaceholder: "https://acme.com",
        step1of3: "Step 1 of 3",
        pane2Title: "Define AI Persona",
        pane2Sub: "What is the primary role of this assistant?",
        personaSupport: "Customer Support",
        personaSupportDesc: "Answer queries based on help docs.",
        personaInternal: "Internal Knowledge Base",
        personaInternalDesc: "Assist employees with internal company data.",
        pane3Title: "You're all set!",
        pane3Sub: "Your project is created. Let's head to the dashboard to upload your first documents.",
        goToDashboard: "Go to Dashboard"
    },

    // Analytics
    analytics: {
        overviewTitle: "Project Overview",
        overviewSub: "Here's what's happening with your AI assistant today.",
        kpis: {
            totalDocs: "Total Documents",
            totalDocsTrend: "+12% this week",
            departments: "Departments",
            departmentsTrend: "2 new this month",
            uniqueClients: "Unique Clients",
            uniqueClientsTrend: "+8% this week",
            totalConvs: "Total Conversations",
            totalConvsTrend: "+24% this week"
        },
        estCost: "Est. Cost:",
        days30: "30 Days",
        activityNewDoc: "New Document Indexed",
        activityQuota: "Quota Warning",
        activityDept: "Department Added",
        documents: "Documents",
        indexedFiles: "Indexed Files",
        departments: "Departments",
        active: "Active",
        clients: "Clients",
        served: "Served",
        connections: "Connections",
        externalSources: "External Sources",
        recentActivity: "Recent Activity",
        viewAll: "View All",
        activityTypes: {
            pdfParsed: "Successfully parsed Q3_Report file",
            apiKeyGen: "New API key generated by admin",
            costLimit: "Cost control limit reached (95%)",
            inviteSent: "Team invite sent to sarah@example.com"
        },
        tokenConsumption: "Token Consumption",
        totalCost: "Total Cost",
        monthlyLimit: "Monthly Limit"
    },

    // Audit
    audit: {
        title: "Chat Audit",
        subTitle: "Review recent AI conversations for quality and accuracy.",
        recentSessions: "Recent Sessions",
        searchPlaceholder: "Search conversations...",
        filters: "Filters",
        sessionDetails: "Session Details",
        selectSession: "Select a session from the list to view details.",
        sessionCost: "Session Cost",
        sourceVerification: "Source Verification",
        verified: "Verified",
        groundedIn: "Grounded in"
    },

    // Billing
    billing: {
        title: "Billing & Subscription",
        subTitle: "Manage your API usage, file quotas, and plan tiers.",
        quotaMonitoring: "Quota Monitoring",
        docUploads: "Document Uploads",
        remaining: "Remaining:",
        vectorStorage: "Vector Storage",
        limit: "Limit:",
        availablePlans: "Available Plans",
        currentPlan: "Current Plan",
        proPlan: "Pro Plan",
        enterprisePlan: "Enterprise",
        starterPlan: "Starter",
        perMonth: "/month",
        features: "Features",
        upgrade: "Upgrade",
        contactSales: "Contact Sales"
    },

    // Knowledge
    knowledge: {
        title: "Knowledge Base",
        subTitle: "Upload PDFs, Markdown, and Text files to train your assistant.",
        uploadDocs: "Upload Documents",
        dragDrop: "Drag & drop your files here",
        selectFiles: "Or click to browse",
        supportedFormats: "Supported: PDF, TXT, MD, DOCX (Max 20MB)",
        uploadSettings: "Upload Settings",
        targetDept: "Target Department",
        deptHelper: "Docs will be isolated to this department's knowledge silo.",
        deptGen: "General Operations",
        deptHR: "HR & Benefits",
        deptSales: "Sales Material",
        deptEng: "IT Support",
        indexedFiles: "Indexed Files",
        refreshStatus: "Refresh Status",
        fileName: "File Name",
        dept: "Dept",
        status: "Status",
        date: "Date",
        actions: "Actions",
        noDocs: "No documents uploaded yet.",
        statusReady: "Ready",
        statusProc: "Processing",
        statusPend: "Pending",
        statusFail: "Failed",
        justNow: "Just now"
    },

    // Playground
    playground: {
        headerMode: "AI Assistant Sandbox (Debug Mode)",
        welcome: "Hello! I am your AI assistant. I'm connected to your knowledge base. How can I help you today?",
        placeholder: "Ask a question about your indexed documents...",
        assistant: "Assistant",
        you: "You",
        typing: "AI is thinking",
        params: "Model Parameters",
        model: "Model",
        temperature: "Temperature (Creativity)",
        topP: "Top P",
        maxTokens: "Max Tokens",
        systemPrompt: "System Prompt",
        traceability: "Traceability Output"
    },

    // Settings
    settingsView: {
        title: "Project Settings",
        subTitle: "Manage your project details, users, and security configuration.",
        general: "General Settings",
        generalSub: "Update fundamental project details.",
        members: "Team Members",
        membersSub: "Manage who has access to this project.",
        security: "Security",
        securitySub: "Update your password.",
        descHelper: "Maximum 50 words about the purpose of this AI.",
        addMember: "Add Member",
        currentPass: "Current Password",
        newPass: "New Password",
        confirmPass: "Confirm Password",
        updatePass: "Update Password"
    },

    // Usage
    usageView: {
        title: "Detailed Usage",
        subTitle: "Monitor your exact consumption, running costs, and hard limits.",
        limitsDetails: "Limit Details",
        costHistory: "Cost History"
    }
};
